"""add updated_at to safety events

Revision ID: f76e6927d6f8
Revises: e7fd0bedf590
Create Date: 2026-09-05 09:58:58.151234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76e6927d6f8'
down_revision: Union[str, Sequence[str], None] = 'e7fd0bedf590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_events', 'updated_at')
    # ### end Alembic commands ###
